services:
  lca-service:
    build:
      context: ./nbla-backend/olca-modules
      dockerfile: Dockerfile
    image: nbla-lca
    container_name: nbla-container-lca
    restart: always
    ports:
      - "${NBLA_LCA_SERVICE_PORT}:${NBLA_LCA_SERVICE_PORT}"

    env_file:
      - .env

    volumes:
      - "G:\\Projects\\project_1\\programming\\Activity_2\\:${NBLA_LCA_SERVICE_DATA_DIR}"

    networks:
      nbla-network:
        aliases:
          - lca.${DOMAIN}


networks:
  nbla-network:
    driver: bridge